---
name: apply
on:
  push:
    branches:
      - main
jobs:
  list:
    uses: ./.github/workflows/workflow_call_list.yaml
    permissions:
      contents: read

  apply:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: write
    name: "apply (${{matrix.target.target}})" # Different job name per root module
    needs: [list] # Run after list
    env:
      # Set environment variables per root module
      TFACTION_TARGET: "${{matrix.target.target}}"
      TFACTION_WORKING_DIR: ${{matrix.target.working_directory}}
      TFACTION_JOB_TYPE: ${{matrix.target.job_type}}
    if: "join(fromJSON(needs.list.outputs.targets), '') != ''" # Skip if no root modules changed
    strategy:
      fail-fast: false # Continue other root modules even if one fails
      matrix:
        target: ${{fromJSON(needs.list.outputs.targets)}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Create GitHub App installation access token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-actions: read
          permission-contents: write
          permission-pull-requests: write
          permission-issues: write

      - uses: suzuki-shunsuke/tfaction@latest
        with:
          action: get-or-create-drift-issue

      - name: Set up
        uses: suzuki-shunsuke/tfaction@latest
        with:
          action: setup
          github_token: ${{ steps.token.outputs.token }}

      - name: terraform init
        uses: suzuki-shunsuke/tfaction@latest
        with:
          action: terraform-init
          github_token: ${{ steps.token.outputs.token }}

      - name: Apply
        uses: suzuki-shunsuke/tfaction@latest
        with:
          action: apply
          github_token: ${{ steps.token.outputs.token }}

      - name: Create follow up PR
        uses: suzuki-shunsuke/tfaction@latest
        if: failure()
        with:
          action: create-follow-up-pr
          github_token: ${{ steps.token.outputs.token }}

      - uses: suzuki-shunsuke/tfaction@latest
        if: always()
        with:
          action: update-drift-issue
          status: ${{job.status}}

      - name: Update related PR branches
        uses: suzuki-shunsuke/tfaction@latest
        if: always()
        with:
          action: update-pr-branch
          github_token: ${{ steps.token.outputs.token }}
