name: test
on: pull_request
jobs:
  list:
    uses: ./.github/workflows/workflow_call_list.yaml
    permissions:
      contents: read

  plan:
    name: "plan (${{matrix.target.target}})" # Different job name per root module
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    needs: [list] # Run after list
    permissions:
      contents: read
    env:
      # Set environment variables per root module
      TFACTION_TARGET: "${{matrix.target.target}}"
      TFACTION_WORKING_DIR: ${{matrix.target.working_directory}}
      TFACTION_JOB_TYPE: ${{matrix.target.job_type}}
    if: "join(fromJSON(needs.list.outputs.targets), '') != ''" # Skip if no root modules changed
    strategy:
      fail-fast: false # Continue other root modules even if one fails
      matrix:
        target: ${{fromJSON(needs.list.outputs.targets)}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Create GitHub App installation access token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Set up
        uses: suzuki-shunsuke/tfaction@latest
        with:
          action: setup
          github_token: ${{ steps.token.outputs.token }}

      - name: terraform init
        uses: suzuki-shunsuke/tfaction@latest
        with:
          action: terraform-init
          github_token: ${{ steps.token.outputs.token }}

      - name: Lint
        uses: suzuki-shunsuke/tfaction@pr/3968
        with:
          action: test
          github_token: ${{ steps.token.outputs.token }}

      - name: Plan
        uses: suzuki-shunsuke/tfaction@latest
        with:
          action: plan
          github_token: ${{ steps.token.outputs.token }}

  delete-comment:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - uses: suzuki-shunsuke/tfaction@latest
        with:
          action: delete-comment
